CREATE TABLE IF NOT EXISTS `chapter` (
    `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `content` LONGTEXT NOT NULL,
    `slug` INT(11),
    `titlenumber` VARCHAR(255),
    `background` LONGTEXT,
    `is_active` BOOLEAN,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `media` (
    `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `content` VARCHAR(255) NOT NULL,
    `url` VARCHAR(255) NOT NULL,
    `chapter_id` INT,
    `type` ENUM('picture', 'video'),
    `is_active` BOOLEAN,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`chapter_id`) REFERENCES `chapter`(`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `user` (
    `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `login` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
